### PR TITLE
Info pages in footer added

### PR DESCRIPTION
**Pull request by keawade**
Needs real data. Also, not quite sure where we want to pull the content from. I'm pretty sure we don't want to make separate templates for what are essentially identical pages just with different text.

### CODE REVIEW

**Comment by keawade** [comment]
Let me know what we need and I'll commit some more to this request.

**Comment by NathanBland** [comment]
Most of these are going to be place holders for now. Generally the terms is like we have permission to use your data or something.

 The help page will fill in more as we build out functionality.

We could make a page schema if we wanted to use them in a eb. Or just put all their data in partial views.

**Comment by NathanBland** [comment]
Most of these are going to be place holders for now. Generally the terms is like we have permission to use your data or something.

 The help page will fill in more as we build out functionality.

We could make a page schema if we wanted to use them in a eb. Or just put all their data in partial views.

**Comment by keawade** [comment]
Partials are easy. I'll work on that now.

**Comment by keawade** [comment]
Okay, we're good to pull this now. (We definitely need to change that filler text, haha)

**Comment by keawade** [comment]
I thought about making partials to drop into the footerpages.jade but ended up just making each one drop directly into layout.jade. There wasn't enough code to justify splitting it up so finely.

**Pull request merged**
